class QuestionBank:
    def __init__(self,quest):
        self.quest=quest

questions = {
    "question_1": {"question": "The sky appears blue due to the scattering of sunlight.", "answer": True},
    "question_2": {"question": "Sound travels faster in air than in water.", "answer": False},
    "question_3": {"question": "The capital of Australia is Sydney.", "answer": False},
    "question_4": {"question": "Water boils at 100°C at sea level.", "answer": True},
    "question_5": {"question": "Venus is the closest planet to the Sun.", "answer": False},
    "question_6": {"question": "Humans have four lungs.", "answer": False},
    "question_7": {"question": "The Great Wall of China can be seen from space with the naked eye.", "answer": False},
    "question_8": {"question": "Lightning is hotter than the surface of the Sun.", "answer": True},
    "question_9": {"question": "Sharks are mammals.", "answer": False},
    "question_10": {"question": "The atomic number of oxygen is 8.", "answer": True},
    "question_11": {"question": "A leap year occurs every 4 years.", "answer": True},
    "question_12": {"question": "Plants convert sunlight into energy through photosynthesis.", "answer": True},
    "question_13": {"question": "Bats are blind.", "answer": False},
    "question_14": {"question": "The human body has four kidneys.", "answer": False},
    "question_15": {"question": "The square root of 64 is 8.", "answer": True},
    "question_16": {"question": "Albert Einstein developed the theory of relativity.", "answer": True},
    "question_17": {"question": "Goldfish have a memory span of only three seconds.", "answer": False},
    "question_18": {"question": "The currency of Japan is the Yen.", "answer": True},
    "question_19": {"question": "Penguins can fly.", "answer": False},
    "question_20": {"question": "There are 365 days in a year.", "answer": True},
    "question_21": {"question": "The speed of light is faster than the speed of sound.", "answer": True},
    "question_22": {"question": "Bananas grow on trees.", "answer": False},  # They grow on large herbs
    "question_23": {"question": "Mount Everest is the tallest mountain in the world.", "answer": True},
    "question_24": {"question": "An octopus has three hearts.", "answer": True},
    "question_25": {"question": "The Sun is a planet.", "answer": False},
    "question_26": {"question": "Mercury is the hottest planet in our solar system.", "answer": False},  # Venus is hotter
    "question_27": {"question": "There are 26 letters in the English alphabet.", "answer": True},
    "question_28": {"question": "New York City is the capital of the USA.", "answer": False},
    "question_29": {"question": "The Mona Lisa was painted by Leonardo da Vinci.", "answer": True},
    "question_30": {"question": "Spiders are insects.", "answer": False},
    "question_31": {"question": "A triangle has three sides.", "answer": True},
    "question_32": {"question": "Elephants are the largest land animals.", "answer": True},
    "question_33": {"question": "Whales are fish.", "answer": False},
    "question_34": {"question": "H2O is the chemical formula for water.", "answer": True},
    "question_35": {"question": "Earth has two moons.", "answer": False},
    "question_36": {"question": "An ostrich can fly.", "answer": False},
    "question_37": {"question": "The Pacific Ocean is the largest ocean on Earth.", "answer": True},
    "question_38": {"question": "The human skeleton is made up of over 200 bones.", "answer": True},
    "question_39": {"question": "Saturn has rings.", "answer": True},
    "question_40": {"question": "A group of lions is called a pack.", "answer": False},  # It's called a pride
    "question_41": {"question": "Chocolate is toxic to dogs.", "answer": True},
    "question_42": {"question": "The brain is the largest internal organ in the human body.", "answer": False},  # It's the liver
    "question_43": {"question": "Photosynthesis occurs in chloroplasts.", "answer": True},
    "question_44": {"question": "Snakes have eyelids.", "answer": False},
    "question_45": {"question": "All mammals give birth to live young.", "answer": False},  # Platypus and echidnas lay eggs
    "question_46": {"question": "The Eiffel Tower is in Berlin.", "answer": False},
    "question_47": {"question": "Diamonds are the hardest natural substance on Earth.", "answer": True},
    "question_48": {"question": "The human heart has four chambers.", "answer": True},
    "question_49": {"question": "Pluto is still classified as a planet in our solar system.", "answer": False},
    "question_50": {"question": "There are five senses in the human body.", "answer": True},
    "question_51": {"question": "The currency of the UK is the Euro.", "answer": False},
    "question_52": {"question": "Birds are warm-blooded animals.", "answer": True},
    "question_53": {"question": "The human body is about 60% water.", "answer": True},
    "question_54": {"question": "An adult human has 32 teeth.", "answer": True},
    "question_55": {"question": "Light travels in a straight line.", "answer": True},
    "question_56": {"question": "A hexagon has eight sides.", "answer": False},  # It has six
    "question_57": {"question": "The sun rises in the west.", "answer": False},
    "question_58": {"question": "The freezing point of water is 0°C.", "answer": True},
    "question_59": {"question": "Jupiter is the largest planet in the solar system.", "answer": True},
    "question_60": {"question": "The lungs are part of the digestive system.", "answer": False},
    "question_61": {"question": "Mars is also known as the Red Planet.", "answer": True},
    "question_62": {"question": "Humans can breathe in space without a suit.", "answer": False},
    "question_63": {"question": "The longest river in the world is the Nile.", "answer": True},
    "question_64": {"question": "Bamboo is a type of grass.", "answer": True},
    "question_65": {"question": "Owls can rotate their heads 360 degrees.", "answer": False},
    "question_66": {"question": "The piano has 88 keys.", "answer": True},
    "question_67": {"question": "The speed of sound is 343 meters per second in air.", "answer": True},
    "question_68": {"question": "Mitochondria are known as the powerhouse of the cell.", "answer": True},
    "question_69": {"question": "Sloths are the fastest land mammals.", "answer": False},
    "question_70": {"question": "Antarctica is the driest continent.", "answer": True},
    "question_71": {"question": "Fire needs oxygen to burn.", "answer": True},
    "question_72": {"question": "Honey never spoils.", "answer": True},
    "question_73": {"question": "Humans evolved from chimpanzees.", "answer": False},  # They share a common ancestor
    "question_74": {"question": "An octagon has 8 sides.", "answer": True},
    "question_75": {"question": "The Amazon rainforest is the largest in the world.", "answer": True},
    "question_76": {"question": "Bats are birds.", "answer": False},
    "question_77": {"question": "Shakespeare wrote 'To be or not to be'.", "answer": True},
    "question_78": {"question": "The chemical symbol for iron is Fe.", "answer": True},
    "question_79": {"question": "The moon is a planet.", "answer": False},
    "question_80": {"question": "Rabbits are rodents.", "answer": False},  # They're lagomorphs
    "question_81": {"question": "C++ is a programming language.", "answer": True},
    "question_82": {"question": "Birds lay eggs.", "answer": True},
    "question_83": {"question": "The boiling point of alcohol is higher than water.", "answer": False},
    "question_84": {"question": "Cats are nocturnal animals.", "answer": True},
    "question_85": {"question": "Lead is heavier than aluminum.", "answer": True},
    "question_86": {"question": "An insect has six legs.", "answer": True},
    "question_87": {"question": "The liver is located on the left side of the human body.", "answer": False},
    "question_88": {"question": "Polar bears are found in Antarctica.", "answer": False},
    "question_89": {"question": "Earth is the third planet from the Sun.", "answer": True},
    "question_90": {"question": "A light year is a unit of time.", "answer": False},
    "question_91": {"question": "The heart is a muscle.", "answer": True},
    "question_92": {"question": "Spiders have six legs.", "answer": False},
    "question_93": {"question": "Tomatoes are vegetables.", "answer": False},  # They're fruits
    "question_94": {"question": "Water expands when it freezes.", "answer": True},
    "question_95": {"question": "The human body has 46 chromosomes.", "answer": True},
    "question_96": {"question": "The Sahara is the largest desert in the world.", "answer": True},
    "question_97": {"question": "Dolphins are fish.", "answer": False},
    "question_98": {"question": "Wolves are herbivores.", "answer": False},
    "question_99": {"question": "A heptagon has seven sides.", "answer": True},
    "question_100": {"question": "Zebras are black with white stripes.", "answer": True}
}

ques=QuestionBank(questions)
